# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 22:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0002_auto_20171120_1941'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidato',
            name='vaga',
        ),
        migrations.AddField(
            model_name='vaga',
            name='candidato',
            field=models.ManyToManyField(to='eleicao.Candidato'),
        ),
    ]
