# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0003_auto_20171120_1945'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidato',
            name='cpf',
            field=models.CharField(max_length=13),
        ),
    ]
