# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 22:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0005_auto_20171120_1947'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eleitor',
            name='idade',
        ),
        migrations.RemoveField(
            model_name='eleitor',
            name='rg',
        ),
    ]
