# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 22:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0006_auto_20171120_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eleitor',
            name='cpf',
            field=models.CharField(max_length=14),
        ),
    ]
