# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 23:17
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0009_token'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='token',
            name='num',
        ),
        migrations.AddField(
            model_name='token',
            name='codigo',
            field=models.IntegerField(default=1, unique=True),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='votacao',
            name='token',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.CASCADE, to='eleicao.Token'),
            preserve_default=False,
        ),
    ]
