# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 23:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0010_auto_20171120_2017'),
    ]

    operations = [
        migrations.AlterField(
            model_name='token',
            name='codigo',
            field=models.CharField(max_length=5, unique=True),
        ),
    ]
