# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-20 23:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0011_auto_20171120_2022'),
    ]

    operations = [
        migrations.RenameField(
            model_name='votacao',
            old_name='consistente',
            new_name='votoBranco',
        ),
    ]
