# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-21 00:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eleicao', '0013_auto_20171120_2111'),
    ]

    operations = [
        migrations.CreateModel(
            name='Eleicao',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('local', models.CharField(max_length=20)),
                ('dataInicio', models.DateTimeField()),
                ('dataFim', models.DateTimeField()),
            ],
        ),
    ]
